# Generated by Django 3.0.3 on 2020-02-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='imgage',
            new_name='image',
        ),
    ]
