# Generated by Django 3.0.3 on 2020-02-16 09:23

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Load models:

    product_category = apps.get_model("mainapp", "ProductCategory")  
    product = apps.get_model("mainapp", "Product")  
    contact_country = apps.get_model("mainapp", "ContactCountry")
    contact = apps.get_model("mainapp", "Contact")  
    
    # Create new category

    product_category_obj = product_category.objects.create(
        pk=1,
        name="home", description="home products")

    # Create new products in this category

    product.objects.create(
        pk=1,
        category=product_category_obj,  # Foreign key
        name="product1",
        image="products_images/product1.jpg",
        short_desc="chair1",
        description="home chair1",
        price="111",
        quantity="11",
    )
    product.objects.create(
        pk=2,
        category=product_category_obj,  # Foreign key
        name="product2",
        image="products_images/product2.jpg",
        short_desc="chair2",
        description="home chair2",
        price="222",
        quantity="22",
    )
    product.objects.create(
        pk=3,
        category=product_category_obj,  # Foreign key
        name="product3",
        image="products_images/product3.jpg",
        short_desc="chair3",
        description="home chair3",
        price="333",
        quantity="33",
    )
    del product_category_obj  # Delete link for category

    # Create new category

    product_category_obj = product_category.objects.create(
        pk=2,
        name="office", description="office products"
    )
    # Create new products in this category

    product.objects.create(
        pk=4,
        category=product_category_obj,  # Foreign key
        name="product1",
        image="products_images/product4.jpg",
        short_desc="chair1",
        description="office chair1",
        price="111",
        quantity="11",
    )
    product.objects.create(
        pk=5,
        category=product_category_obj,  # Foreign key
        name="product2",
        image="products_images/product5.jpg",
        short_desc="chair2",
        description="office chair2",
        price="222",
        quantity="22",
    )
    product.objects.create(
        pk=6,
        category=product_category_obj,  # Foreign key
        name="product3",
        image="products_images/product6.jpg",
        short_desc="chair3",
        description="office chair3",
        price="333",
        quantity="33",
    )
    del product_category_obj  # Delete link for category

    # Create new category

    product_category_obj = product_category.objects.create(
        pk=3,
        name="furniture", description="furniture products")

    # Create new products in this category

    product.objects.create(
        pk=7,
        category=product_category_obj,  # Foreign key
        name="product1",
        image="products_images/product7.jpg",
        short_desc="chair1",
        description="furniture chair1",
        price="111",
        quantity="11",
    )
    product.objects.create(
        pk=8,
        category=product_category_obj,  # Foreign key
        name="product2",
        image="products_images/product8.jpg",
        short_desc="chair2",
        description="furniture chair2",
        price="222",
        quantity="22",
    )
    del product_category_obj  # Delete link for category

    # Create new category

    product_category_obj = product_category.objects.create(
    pk=4,
    name="modern", description="modern products")

    # Create new products in this category

    product.objects.create(
        pk=9,
        category=product_category_obj,  # Foreign key
        name="product1",
        image="products_images/product9.jpg",
        short_desc="chair1",
        description="modern chair1",
        price="111",
        quantity="11",
    )
    product.objects.create(
        pk=10,
        category=product_category_obj,  # Foreign key
        name="product2",
        image="products_images/product10.jpg",
        short_desc="chair2",
        description="modern chair2",
        price="222",
        quantity="22",
    )
    del product_category_obj  # Delete link for category

    # Create new category

    product_category_obj = product_category.objects.create(
    pk=5,
    name="classic", description="classic products")

    # Create new products in this category

    product.objects.create(
        pk=11,
        category=product_category_obj,  # Foreign key
        name="product1",
        image="products_images/product11.jpg",
        short_desc="chair1",
        description="classic chair1",
        price="111",
        quantity="11",
    )
    product.objects.create(
        pk=12,
        category=product_category_obj,  # Foreign key
        name="product2",
        image="products_images/product12.jpg",
        short_desc="chair2",
        description="classic chair2",
        price="222",
        quantity="22",
    )
    del product_category_obj  # Delete link for category

    # Create contacts in each country

    contact_country_obj = contact_country.objects.create(
    pk=1,
    name="Thailand", info="Thailand contacts")
    contact.objects.create(
        pk=13,
        country=contact_country_obj,  # Foreign key
        phone="9999-1234-5678", 
        email="thailand@interior.com", 
        address="9999 W 1st St, 90001 Thailand",
        image="contact_images/location-image.jpg",
        short_desc="location in Thailand",
    )
    del contact_country_obj

    contact_country_obj = contact_country.objects.create(
        pk=2,
        name="Vietnam", info="Vietnam contacts")
    contact.objects.create(
        pk=14,
        country=contact_country_obj,  # Foreign key
        phone="8888-1234-5678",
        email="vietnam@interior.com",
        address="8888 W 1st St, 90001 Vietnam",
        image="contact_images/location-image.jpg",
        short_desc="location in Vietnam",
    )
    del contact_country_obj

    contact_country_obj = contact_country.objects.create(
    pk=3,
    name="Costa-Rica", info="Costa-Rica contacts")
    contact.objects.create(
        pk=15,
        country=contact_country_obj,  # Foreign key
        phone="7777-1234-5678",
        email="costa-rica@interior.com", 
        address="7777 W 1st St, 90001 Costa-Rica",
        image="contact_images/location-image.jpg",
        short_desc="location in Costa-Rica",
    )
    del contact_country_obj


def reverse_func(apps, schema_editor):

    # Load models:
    
    product_category = apps.get_model("mainapp", "ProductCategory")  
    contact_country = apps.get_model("mainapp", "ContactCountry")

    # Delete all objects

    product_category.objects.all().delete()
    contact_country.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200213_1639'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
