# Generated by Django 3.0.3 on 2020-02-16 11:19

from django.conf import settings
from django.db import migrations


def forwards_func(apps, schema_editor):
    if settings.DEBUG:
        # Only in DEBUG mode!
        try:
            from authapp.models import ShopUser

            ShopUser.objects.create_superuser(
                "django", "root@geekbrains.com", "geekbrains", age=32
            )
        except:
            print("Can't create super user for debug")


def reverse_func(apps, schema_editor):
    if settings.DEBUG:
        # Only in DEBUG mode!
        try:
            from authapp.models import ShopUser

            ShopUser.objects.create_superuser(
                "django", "root@geekbrains.com", "geekbrains", age=32
            )
        except:
            print("Can't delete super user for debug")


class Migration(migrations.Migration):

    dependencies = [("authapp", "0001_initial")]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
